name: cifar10_pytorch_18278
hyperparameters:
  learning_rate: 2.29e-2
  learning_rate_decay: 0
  cnv_out_ch_0: 512
  cnv_stride_0: 1
  cnv_pool_0: True
  cnv_out_ch_1: 512
  cnv_stride_1: 1
  cnv_pool_1: True
  cnv_out_ch_2: 64
  cnv_stride_2: 1
  cnv_pool_2: True
  cnv_out_ch_3: 128
  cnv_stride_3: 1
  cnv_pool_3: True
  cnv_out_ch_4: 32
  cnv_stride_4: 2
  cnv_pool_4: True
  cnv_out_ch_5: 256
  cnv_stride_5: 1
  cnv_pool_5: True
  int_fc_feat_1: 128
  int_fc_feat_2: 32
  weight_bit_width: 1
  act_bit_width: 1
  pool_size: 2
  kern_size: 2
  global_batch_size: 100
profiling:
  enabled: true
  begin_on_batch: 0
  end_after_batch: 32000
records_per_epoch: 50000
searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 5000
entrypoint: model_def:CIFARTrial
min_validation_period:
  epochs: 1
environment:
  image: "determinedai/environments:cuda-11.1-pytorch-1.9-lightning-1.3-tf-2.4-gpu-0.17.6"
checkpoint_storage:
  type: shared_fs
  host_path: /xilinx/scratch/determined
resources:
  slots_per_trial: 1
  max_slots: 1
